### ISSUE TITLE
Strange black/blueish bars on some images

### ISSUE THREAD

**Issue by NueSB** [Wunkolo/SaiThumbs#1]
Not too sure what's causing it, it's only popping up on two of my files. the thumbnails show up fine in sai's Open dialog

(file explorer on the left, sai on the right)
![image](https://user-images.githubusercontent.com/22834910/31797509-9b86ff3e-b4fc-11e7-85c7-954501ce930a.png)

**Comment by Wunkolo** [comment]
Did some debugging and it looks the way I have it implementing the underlying virtual file system of `.sai` involved it reading the [TableBlock](https://github.com/Wunkolo/libsai#decryption) as if it was actual file data when it should be skipping it. The blue bar you see there is the `TableBlock` being interpreted as raw pixel data heh. Working on a fix.

**Comment by Wunkolo** [comment]
Should be fixed now!
