### ISSUE TITLE
Unable to download on Windows 10

### ISSUE THREAD

**Issue by d-floe** [Wunkolo/SaiThumbs#2]
I was able to get this installed perfectly fine on my Windows 7 64x Desktop computer but for some reason trying to install this on my Windows 10 Pro 64x Laptop doesn't seem to do anything. Ive tried to run it as administrator and restarting my computer but nothing seems to work at all. Ive also cleared all my system thumbnail files and still nothing. I even tried the 32 bit version. Not quite sure what's going on, your demo was in Windows 10 so I'm a little confused as to why this isn't working.

**Comment by Wunkolo** [comment]
Hm that's strange.
Try starting from a clean slate:
Run "uninstall.bat" and run `Disk Cleanup` on your thumbnails so that you're back to square one.

After that, `hold down shift` and `right click` at the same time in the folder where `SaiThumbs.dll` is in and you should see:
![image](https://user-images.githubusercontent.com/644247/31830639-b24c9872-b575-11e7-8880-746a308c3dd7.png)
or it might say `Open command window here`.
Try entering the command `regsvr32 SaiThumbs.dll` and it should show a diagnostic message on if it installed properly or not:
![image](https://user-images.githubusercontent.com/644247/31830740-018b3538-b576-11e7-9f86-e93749d2e0e0.png)
It's possible that you might need to be running the installer as administrator as well:
![image](https://user-images.githubusercontent.com/644247/31830765-1931c27e-b576-11e7-9379-c517a8716754.png)

**Comment by d-floe** [comment]
I tried your suggestion and this is what I got.
![image](https://user-images.githubusercontent.com/31980883/31847929-8e16481a-b5eb-11e7-824e-0c5ff79a9718.png)
Running as administrator seems to do nothing either.
I even redownloaded the ZIP but it doesnt seem to change anything.

**Comment by Wunkolo** [comment]
This seems to be an error that happens when you try to install a dll of a different architecture than your system(ex: registering a 32-bit DLL on a 64-bit Windows or 64-bit DLL on a 32-bit Windows).
Are you sure you have the correct version for your architecture downloaded?

**Comment by d-floe** [comment]
Well I tried this on the 32 bit version and I got this
![image](https://user-images.githubusercontent.com/31980883/31848844-106f7238-b5ff-11e7-9406-6e6eec16b5bd.png)
It was great news but to my surprise, it didn't work. My thumbnails are still broken.

**Comment by Wunkolo** [comment]
This is really weird as you shouldn't even be able to install the 32-bit version on a 64-bit machine at all without putting it through SysWoW64 but the 64-bit version that is native to your system refuses to install. Are you [certain your machine is 64-bit](https://support.wdc.com/knowledgebase/answer.aspx?ID=9405#win10)? Try downloading the latest version on itch.io that I just recently updated and starting from a clean slate before installing.
When SaiThumbs is fully uninstalled then you should find that the registry entry for:
`HKEY_CURRENT_USER\Software\Classes\.sai` and `HKEY_CURRENT_USER\Software\Classes\CLSID\{35788B9B-04AB-4B75-AB3A-1ED403AFC746}` is *completely* gone.

You can check if the values exist or not by opening windows powershell and entering the commands:

`Get-ItemProperty 'HKCU:\Software\Classes\.sai'`
and
`Get-ItemProperty 'HKCU:\Software\Classes\CLSID\{35788B9B-04AB-4B75-AB3A-1ED403AFC746}'`

If both commands return an error after you run `uninstall.bat` then they both do not exist and you have a fresh slate to re-install.

If either exist then you currently have an installation that is possibly overriding each of your further attempts to reinstall.

**Comment by Sakuyamon** [comment]
I got a win10 x64 computer and get the same errors... I tried both versions of the install and gone through everything said here but the error remain the same...

**Comment by d-floe** [comment]
Looks like the issue resolved itself?
After revisiting my laptop the next day it seems my thumbnails are working now after my previous post. Thanks for the help Wunkolo!!

**Comment by Wunkolo** [comment]
@Sakuyamon are you still facing this issue?

**Comment by actualpedro** [comment]
I have the same issue, running win10 x64, with the x64 version. Tried uninstalling and it still gives me the same error message, as well as running it with PowerShell or with admin privileges. Also tried adding the full file paths to the batch files, no change.

Also checked the registry just in case - no `HKEY_CURRENT_USER\Software\Classes\.sai` and `HKEY_CURRENT_USER\Software\Classes\CLSID\{35788B9B-04AB-4B75-AB3A-1ED403AFC746}` entries.

**Comment by Lady-Luck** [comment]
Hi, I'm having this problem as well. I ran install.bat as administrator as well and I did it from a directory without any security. Windows 10 x64 Fall Update.

**Comment by Lady-Luck** [comment]
aha... I see the problem.

it's a 'current directory' issue.

https://www.codeproject.com/Tips/119828/Running-a-bat-file-as-administrator-Correcting-cur

**Comment by Lady-Luck** [comment]
aha... I see the problem. it's a 'current directory' issue.

https://www.codeproject.com/Tips/119828/Running-a-bat-file-as-administrator-Correcting-cur

Just add these two lines to the top of both your batch scripts:

@setlocal enableextensions
@cd /d "%~dp0"

**Comment by Wunkolo** [comment]
@Sakuyamon @actualpedro have any of you tried these edits? You should be able to right-click the `install.bat` file and click `edit` to add these two lines. If it works I'll be sure to add it to the repo!

**Comment by Sakuyamon** [comment]
I tried it... But it don't seem to work... It only stopped me from getting error messages when I installed it as an admin. No changes to my thumbnails...

**Comment by actualpedro** [comment]
Sorry for the late reply! Tried it both with and without admin permissions, still results in the same error.

**Comment by Pikachewy** [comment]
Hello,
I've been having the exact same issue when trying to install to a freshly installed copy of Windows 10, spent ages tinkering with the registry but I think I've found a potential fix. All I did was install Microsoft Office, then install SaiThumbs normally and now it works like a charm! Hopefully this can help others facing the same problem.

**Comment by Gameplayer9198** [comment]
Found this extension today as my windows 10 install was still fresh, and error "The module "SaiThumbs.dll" Failed to load...." was all i was getting so here i am on this issue page.

So.. I found the issue from Pikachewys advice and deducted Runtimes, tested and i was correct. You need vcredist (Visual C++ Redistributables) not sure which version but i installed 2012 through 2017. 🤔

**Comment by Gameplayer9198** [comment]
@Wunkolo Users need Visual C++ Redistributables 2017

Microsoft Visual C++ Redistributable for Visual Studio 2017
(Its Recommend to install both if you on a 64bit System) 

x64: [https://go.microsoft.com/fwlink/?LinkId=746572](https://go.microsoft.com/fwlink/?LinkId=746572) <-- Direct Download

x86: [https://go.microsoft.com/fwlink/?LinkId=746571](https://go.microsoft.com/fwlink/?LinkId=746571) <-- Direct Download

**Comment by Wunkolo** [comment]
Thank you for that. I pushed a commit that should statically link the runtimes so that the redist should not be needed to make installation easier.
@Pikachewy @actualpedro @Sakuyamon 
Lemme know if the latest version works for you! I updated the [itch.io page](https://wunkolo.itch.io/saithumbs) with the updated version.
