### ISSUE TITLE
Previews do not show for Japanese characters

### ISSUE THREAD

**Issue by Jaeden7060** [Wunkolo/SaiThumbs#3]
Previews do not show when Japanese characters and full-width alphanumeric characters are in a filename.
Could possibly also apply to other languages and character sets.

**Comment by Wunkolo** [comment]
Seems some layers of the file IO implementations doesn't properly implement unicode. Working on a fix!

**Comment by Wunkolo** [comment]
Should be fixed now on the latest build! Uninstall your current version with `uninstall.bat` and [redownload the latest build from itch.io to get it](https://wunkolo.itch.io/saithumbs)! Should now work with unicode filenames
![image](https://user-images.githubusercontent.com/644247/31848411-09ecd332-b5e7-11e7-928b-5208699cf130.png)
