### ISSUE TITLE
Module failed to load

### ISSUE THREAD

**Issue by Wakor** [Wunkolo/SaiThumbs#4]
When double-clicking install, I get an error titled RegSvr32 with the following message:

The module "SaiThumbs.dll' failed to load.

Make sure the binary is stored at the specified path or debug it to check for problems with the binary or dependent .DLL files.

The specified module could not be found. 

![tumblr_owsyrel3z51watromo1_1280](https://user-images.githubusercontent.com/33079633/31980011-56c32352-b90f-11e7-9ea2-f0eaf02a8fb9.png)

**Comment by Wunkolo** [comment]
This is the same symptoms as #2 which I am currently still trying to figure out and recreate at the moment.
