### ISSUE TITLE
Reminder: Update batch files

### ISSUE THREAD

**Issue by Baddest-Juju** [Wunkolo/SaiThumbs#5]
install.bat
```
@setlocal enableextensions
@cd /d "%~dp0"
regsvr32 SaiThumbs.dll
```

uninstall.bat
```
@setlocal enableextensions
@cd /d "%~dp0"
regsvr32 /u SaiThumbs.dll
```

Batch files, when ran as administrator, have a default working directory of C:\Windows\System32 rather than the folder they were ran in. This fixes that.

**Comment by Wunkolo** [comment]
Added!
