### ISSUE TITLE
Doesn't work on Windows 10 after updates

### ISSUE THREAD

**Issue by alexandervrs** [Wunkolo/SaiThumbs#6]
Hello, I've been using the shell extension for a while now, it was very useful for me but unfortunately it stopped working on Windows 10 after a few updates. It happened both at my home and work PC. The thumbnails just don't show up anymore. 
I tried to clear the thumbnail cache, delete any .sai references in registry, register and unregister the dlls, use different versions of the dll files and move them to other folders. Add those folders to PATH. Nothing really worked anymore. Can this be looked into?

**Comment by Wunkolo** [comment]
Thanks for the report. I can look into this. Likely some API behavior changes of some sort or something.
[What specific build of Windows 10 are you on?](https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running)

**Comment by alexandervrs** [comment]
Windows 10 Pro, OS build 18363.535

**Comment by Wunkolo** [comment]
Been doing some research and I feel that it might be related to some Windows SDK update or Visual C++ runtime incompatibility.
I haven't had a chance to re-create the issue but see if this `.dll` file gives you any different results. I have it using the Visual Studio 2019 build chain.
https://transfer.sh/4CGJn/SaiThumbs.dll
`MD5: 67805b0b34a8a6fe303dd0446c84bc0e`

**Comment by alexandervrs** [comment]
I re-installed with the new .dll and it doesn't seem to have changed anything sadly.
I also tried using latest and earlier versions of SAI to see if that was the issue, but same result

**Comment by Wunkolo** [comment]
Just updated to `18363.592`(Windows 10 home, Version 1909) to try and recreate the issue myself and wasn't able to recreate the issue for some reason despite clearing the thumbnails too.
Can you possibly try updating again to see if the issue persists?

**Comment by alexandervrs** [comment]
Sorry for the late reply but I did a clean install with the latest version and it doesn't seem to reproduce now. So probably Windows was at fault here. If I see the issue again, I'll try to deduct what caused it right away
