### ISSUE TITLE
And SAI2

### ISSUE THREAD

**Issue by Li-An** [Wunkolo/SaiThumbs#7]
Hello, do you plan to do the same for SAI2 ?

**Comment by Wunkolo** [comment]
Hey! I get this quite a lot on the itch.io page haha. Perhaps I will move on to Sai2 though I personally don't use Sai2 enough to really have the motive to invest the amount of work into it at the moment. But after all this demand I may just line a Sai2 reverse engineering project up at some point to create a `libsai2` and `Sai2Thumbs` project. Thank you for showing interest!

**Comment by Li-An** [comment]
Thanks for your answer. I can understand that you may not be interested in such a work if you don’t work on SAI2.
